# Generated by Django 4.0.2 on 2022-03-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
                ('Url', models.CharField(max_length=2083)),
                ('Image_URL', models.CharField(max_length=2083)),
                ('Button_label', models.CharField(max_length=255)),
            ],
        ),
    ]
